title: Joshua Alcantara
description: Leader | Writer | Cybersecurity
site_title: '@DarkSymphonie - Joshua Alcantara'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: DarkSymphonie
blog_url: https://darksymphonie.wixsite.com/darksym
email: Darksymphonie@protonmail.com
keybase_username: in/joshuaisaaacalcantara/
twitter_username: DarkSymphonie_

# absolute or relative
profile_picture: assets/images/Fireeepic.jpeg

# Google Analytics ID
google_analytics: UA-213781006-1
