title: Joshua Alcantara
description: Leader| CyberSecurity | Tech |  
site_title: '@DarkSymphonie - Joshua Alcantara'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: DarkSymphonie
blog_url: https://www.nagekar.com
email: Darksymphonie@protonmail.com
keybase_username: in/joshuaisaaacalcantara/
twitter_username: Darksymponie
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/Fireeepic.jpeg

# Google Analytics ID
google_analytics: UA-213781006-1
